"""make pending balance field nullable

Revision ID: 23d455d93093
Revises: a3512390412c
Create Date: 2024-11-26 22:30:13.310402

"""
from typing import Sequence, Union
import sqlmodel

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '23d455d93093'
down_revision: Union[str, None] = 'a3512390412c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['uid'])

    with op.batch_alter_table('celery_beat', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['uid'])

    with op.batch_alter_table('matrix_pool', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['uid'])

    with op.batch_alter_table('matrix_users', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['uid'])

    with op.batch_alter_table('peending_transactions', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['uid'])

    with op.batch_alter_table('referrals', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['uid'])

    with op.batch_alter_table('token_meter', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['uid'])

    with op.batch_alter_table('user_stakings', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['uid'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['uid'])

    with op.batch_alter_table('wallets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pendingBalance', sa.Numeric(scale=9), nullable=True))
        batch_op.create_unique_constraint(None, ['uid'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wallets', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('pendingBalance')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('user_stakings', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('token_meter', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('referrals', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('peending_transactions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('matrix_users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('matrix_pool', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('celery_beat', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
