"""Migration Message

Revision ID: 24caad7e7180
Revises: 81a5b2764863
Create Date: 2024-11-18 16:52:28.266899

"""
from typing import Sequence, Union
import sqlmodel

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '24caad7e7180'
down_revision: Union[str, None] = '81a5b2764863'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_stakings', sa.Column('nextRoiIncrease', postgresql.TIMESTAMP(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_stakings', 'nextRoiIncrease')
    # ### end Alembic commands ###
