"""Migration Message

Revision ID: 3975de9804c0
Revises: 5f8fb9bce003
Create Date: 2024-11-17 05:45:27.813688

"""
from typing import Sequence, Union
import sqlmodel

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3975de9804c0'
down_revision: Union[str, None] = '5f8fb9bce003'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('passwordHash', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.drop_column('wallets', 'passwordHash')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wallets', sa.Column('passwordHash', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('users', 'passwordHash')
    # ### end Alembic commands ###
