"""Migration Message

Revision ID: 46f74f0b2253
Revises: 7da3ea078cf1
Create Date: 2024-11-16 16:26:53.235325

"""
from typing import Sequence, Union
import sqlmodel

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '46f74f0b2253'
down_revision: Union[str, None] = '7da3ea078cf1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('referrals', sa.Column('level', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('referrals', 'level')
    # ### end Alembic commands ###
