"""Migration Message

Revision ID: 55f1873cdd22
Revises: 8297fe180b0b
Create Date: 2024-11-22 12:40:20.787806

"""
from typing import Sequence, Union
import sqlmodel

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '55f1873cdd22'
down_revision: Union[str, None] = '8297fe180b0b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('totalReferralsStakes', sa.Numeric(scale=9), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('totalReferralsStakes')

    # ### end Alembic commands ###
