"""Removed task_sig from CeleryBeat model

Revision ID: 5fffe06e0245
Revises: 11ddb560031b
Create Date: 2024-11-21 06:11:21.321492

"""
from typing import Sequence, Union
import sqlmodel

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5fffe06e0245'
down_revision: Union[str, None] = '11ddb560031b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('celery_beat', 'task_sig')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('celery_beat', sa.Column('task_sig', sa.VARCHAR(length=500), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
