"""Migration Message

Revision ID: 6fb7855457ad
Revises: 5ad56af22bfb
Create Date: 2024-11-16 16:21:56.993581

"""
from typing import Sequence, Union
import sqlmodel

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6fb7855457ad'
down_revision: Union[str, None] = '5ad56af22bfb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('referrals', sa.Column('referrerUserId', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('referrals', 'referrerUserId')
    # ### end Alembic commands ###
