"""Migration Message

Revision ID: 7da3ea078cf1
Revises: 6fb7855457ad
Create Date: 2024-11-16 16:24:45.996208

"""
from typing import Sequence, Union
import sqlmodel

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7da3ea078cf1'
down_revision: Union[str, None] = '6fb7855457ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('referrals', sa.Column('referrerUid', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'referrals', 'users', ['referrerUid'], ['uid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'referrals', type_='foreignkey')
    op.drop_column('referrals', 'referrerUid')
    # ### end Alembic commands ###
