"""Removed task_sig from CeleryBeat model

Revision ID: 9dad3513d24f
Revises: 5fffe06e0245
Create Date: 2024-11-21 08:29:57.317434

"""
from typing import Sequence, Union
import sqlmodel

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9dad3513d24f'
down_revision: Union[str, None] = '5fffe06e0245'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('usedSpeedBoost', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'usedSpeedBoost')
    # ### end Alembic commands ###
