"""Migration Message

Revision ID: a08729f22fe6
Revises: b251a211db86
Create Date: 2024-11-21 19:04:09.926803

"""
from typing import Sequence, Union
import sqlmodel

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a08729f22fe6'
down_revision: Union[str, None] = 'b251a211db86'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'peending_transactions', ['uid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'peending_transactions', type_='unique')
    # ### end Alembic commands ###
