"""Migration Message

Revision ID: aabf1acbd851
Revises: 55f1873cdd22
Create Date: 2024-11-22 12:49:06.761142

"""
from typing import Sequence, Union
import sqlmodel

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aabf1acbd851'
down_revision: Union[str, None] = '55f1873cdd22'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('referrals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stake', sa.Numeric(scale=9), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('referrals', schema=None) as batch_op:
        batch_op.drop_column('stake')

    # ### end Alembic commands ###
